# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: es_AR
    php_errors:
        log: true
    session:
        handler_id: null
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 0
        gc_maxlifetime: 0
        gc_probability: 1
        gc_divisor: 1000
        save_path: '%kernel.cache_dir%/sessions'
        metadata_update_threshold: 0
    
    # Enable these if needed
    # esi: true
    # fragments: true

when@test:
    framework:
        csrf_protection: true
        form: true
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
