version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: sistema-interno-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: sistema-interno
      MYSQL_USER: gustavo
      MYSQL_PASSWORD: 12345678
    ports:
      - "3313:3306"  # Map host port 3313 to container port 3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db_data:
